name: Update README

on:
  schedule:
    - cron: '0 10 * * *'

jobs:
  update_readme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install requests

    - name: Run script
      run: python update_readme.py

    - name: Commit and push changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Update README with new stats
        push_options: '--force' # Добавляем force push, если это необходимо
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Добавляем токен